spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
      - id: employeeModule
        uri: lb://USER-SERVICE
        predicates:
        - Path=/user/**
      - id: addressModule
        uri: lb://ADDRESS-SERVICE
        predicates:
        - Path=/address/**